server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345
  jackson:
    serialization:
      write-durations-as-timestamps: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 5MB
feign:
  user:
    url: http://localhost:8081/api/user

minio:
  url: http://minio-file-service:9000
  username: admin
  password: admin123
  bucket: first-bucket